name: Build & Push Docker images to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Configurer les credentials AWS à partir des secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3) Login à Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4) Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5) Build & Push backend
      - name: Build & Push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.ECR_BACKEND_REPO }}:latest

      # 6) Build & Push frontend
      - name: Build & Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          push: true
          tags: |
            ${{ secrets.ECR_FRONTEND_REPO }}:latest